repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: check-yaml
      - id: fix-byte-order-marker
  - repo: https://github.com/google/yamlfmt
    rev: "v0.11.0"
    hooks:
      - id: yamlfmt
