name: Lint
on: pull_request
jobs:
  install-invoke:
    name: Install Invoke-Atomic
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Run lint checks
        shell: pwsh
        run: |
          Install-Module -Name PSScriptAnalyzer -Force
          Invoke-ScriptAnalyzer -Recurse ./ -Settings ./PSScriptAnalyzerSettings.psd1 -Fix
      - name: Check whether there are any file changes
        shell: bash
        run: |
          git diff --exit-code
