name: publish-powershell-gallery
on:
  push:
    branches: [ master ]
    tags: [ 'v*.*.*' ]
jobs:
  publish-powershell-gallery:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        
      - name: publishing
        run: |
          Install-Module -Name powershell-yaml -Force
          Publish-Module -Path '.' -NuGetApiKey ${{ secrets.PGALLERY }}
        shell: pwsh




